### ISSUE TITLE
混淆有问题

### ISSUE THREAD

**Issue by repeatio** [ipsmap/IpsmapSDK-Android#1]
混淆后找不到com.parse。
去parse-sdk把所有规则复制了一遍，才解决的：
-keepnames class com.parse.** { *; }
-keepattributes *Annotation*
-keepattributes Signature
-dontwarn okio.**

**Comment by libertyfree** [comment]
请问你需要我们对你开放parse吗?你使用parse吗?

**Comment by repeatio** [comment]
额，我是说缺少了混淆规则。
是ipsmapSDk使用了parse，不是我。
可能直接复制过来的文本格式造成了误解，已删改。

**Comment by libertyfree** [comment]
我们sdk内部做了混淆规则,对外接口不需要了解parse
