### ISSUE TITLE
demo不能正常运行

### ISSUE THREAD

**Issue by snsdTJ** [ipsmap/IpsmapSDK-Android#2]
demo不能正常运行，运行时报下面错误
Error:The SDK directory 'E:\OneDrive\AS\exercise\IndoorNav\IpsmapSDK-Android-master\Users\liberty\Library\Android\sdk' does not exist.

Consult IDE log for more details (Help | Show Log)

**Comment by libertyfree** [comment]
请给我看一下日志,请问你是我们的商业的合作伙伴吗
